"""create_questions_table

Revision ID: 279350d0557c
Revises: 20d784397d84
Create Date: 2026-02-10 23:41:01.796131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '279350d0557c'
down_revision: Union[str, None] = '20d784397d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_level', create_type=False), nullable=False),
    sa.Column('question_type', postgresql.ENUM('coding', 'mcq', 'fill_in_blank', 'sql', 'debugging', name='question_type', create_type=False), server_default=sa.text("'coding'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('sample_test_cases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Public test cases shown to students: [{input: "...", output: "..."}]'),
    sa.Column('hidden_test_cases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Hidden test cases for evaluation'),
    sa.Column('max_score', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), server_default=sa.text('60'), nullable=True),
    sa.Column('memory_limit_mb', sa.Integer(), server_default=sa.text('256'), nullable=True),
    sa.Column('allowed_languages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["python", "cpp", "java", "javascript"]\'::jsonb'), nullable=True),
    sa.Column('starter_code', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True, comment='Language-specific starter code: {python: "def solve():", cpp: "..."}'),
    sa.Column('solution_approach', sa.Text(), nullable=True),
    sa.Column('solution_code', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='Topic tags: ["arrays", "dynamic-programming", "graphs"]'),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('company_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('total_submissions', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('successful_submissions', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.0'), nullable=True),
    sa.Column('source_platform', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_score > 0', name='check_questions_max_score_positive'),
    sa.CheckConstraint('time_limit_seconds > 0', name='check_questions_time_limit_positive'),
    sa.CheckConstraint('total_submissions = 0 OR successful_submissions <= total_submissions', name='check_questions_submissions_consistency'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    comment='Coding questions and problem statements for assessments'
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_slug'), 'questions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_slug'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
