"""create_admin_activity_log

Revision ID: 6b0dbf7dc97b
Revises: a60796c7eb89
Create Date: 2026-02-10 23:35:01.456728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6b0dbf7dc97b'
down_revision: Union[str, None] = 'a60796c7eb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('create', 'update', 'delete', 'export', 'import', 'login', 'logout', 'permission_change', 'bulk_operation')", name='check_admin_action_type_valid'),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_activity_action_type', 'admin_activity_log', ['action_type'], unique=False)
    op.create_index('idx_admin_activity_admin_user_id', 'admin_activity_log', ['admin_user_id'], unique=False)
    op.create_index('idx_admin_activity_created_at', 'admin_activity_log', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_admin_activity_resource', 'admin_activity_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_admin_activity_log_id'), 'admin_activity_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_activity_log_id'), table_name='admin_activity_log')
    op.drop_index('idx_admin_activity_resource', table_name='admin_activity_log')
    op.drop_index('idx_admin_activity_created_at', table_name='admin_activity_log')
    op.drop_index('idx_admin_activity_admin_user_id', table_name='admin_activity_log')
    op.drop_index('idx_admin_activity_action_type', table_name='admin_activity_log')
    op.drop_table('admin_activity_log')
    # ### end Alembic commands ###
