"""create_submissions_table

Revision ID: 7c2fa130e6d5
Revises: 83ea4a115c53
Create Date: 2026-02-10 23:53:28.954569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c2fa130e6d5'
down_revision: Union[str, None] = '83ea4a115c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('language', postgresql.ENUM('python', 'cpp', 'java', 'javascript', 'c', 'csharp', 'ruby', 'go', 'rust', 'kotlin', 'swift', name='programming_language', create_type=False), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'accepted', 'wrong_answer', 'time_limit', 'memory_limit', 'runtime_error', 'compile_error', 'internal_error', name='submission_status', create_type=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('total_test_cases', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('passed_test_cases', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('failed_test_cases', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.0'), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_used_kb', sa.Integer(), nullable=True),
    sa.Column('test_case_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='Detailed test case results: [{passed: true, time: 12, memory: 512}]'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('compile_errors', sa.Text(), nullable=True),
    sa.Column('judge0_token', sa.String(length=100), nullable=True),
    sa.Column('judge0_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('submission_number', sa.Integer(), nullable=False, comment='Sequential submission number per student-question pair'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('passed_test_cases >= 0 AND failed_test_cases >= 0 AND passed_test_cases + failed_test_cases <= total_test_cases', name='check_submissions_test_cases_valid'),
    sa.CheckConstraint('score >= 0 AND score <= max_score', name='check_submissions_score_range'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Student code submissions with execution results'
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
