"""create_students_table

Revision ID: 99b3c4f2568c
Revises: 0e5f3cd85f6f
Create Date: 2026-02-10 23:11:28.154480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99b3c4f2568c'
down_revision: Union[str, None] = '0e5f3cd85f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Link to core user account'),
    sa.Column('roll_number', sa.String(length=50), nullable=False, comment='University roll number'),
    sa.Column('branch', postgresql.ENUM('computer_science', 'information_technology', 'electronics', 'electrical', 'ai_ml', name='branch_type', create_type=False), nullable=False),
    sa.Column('batch_year', sa.Integer(), nullable=False, comment='Graduation batch year (e.g. 2025)'),
    sa.Column('current_year', postgresql.ENUM('first', 'second', 'third', 'fourth', name='academic_year', create_type=False), nullable=False),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True, comment='Cumulative Grade Point Average'),
    sa.Column('readiness_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.0'), nullable=False, comment='Calculated placement readiness score (0-100)'),
    sa.Column('last_assessment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leetcode_stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Cached LeetCode statistics: {easy: 10, medium: 5, hard: 2, total: 17, rank: 1234}'),
    sa.Column('codeforces_stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Cached CodeForces statistics'),
    sa.Column('codechef_stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Cached CodeChef statistics'),
    sa.Column('geeksforgeeks_stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Cached GeeksForGeeks statistics'),
    sa.Column('hackerrank_stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Cached HackerRank statistics'),
    sa.Column('leetcode_username', sa.String(length=100), nullable=True),
    sa.Column('codeforces_username', sa.String(length=100), nullable=True),
    sa.Column('codechef_username', sa.String(length=100), nullable=True),
    sa.Column('geeksforgeeks_username', sa.String(length=100), nullable=True),
    sa.Column('hackerrank_username', sa.String(length=100), nullable=True),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('resume_url', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Array of skill tags: ["Python", "JavaScript", "React"]'),
    sa.Column('preferred_roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Preferred job roles: ["Backend Developer", "Data Analyst"]'),
    sa.Column('expected_ctc_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_ctc_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_problems_solved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('problems_solved_last_week', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_streak_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stats_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_completion_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.0'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('batch_year >= 2020 AND batch_year <= 2050', name='check_batch_year_range'),
    sa.CheckConstraint('cgpa >= 0 AND cgpa <= 10', name='check_cgpa_range'),
    sa.CheckConstraint('expected_ctc_min IS NULL OR expected_ctc_max IS NULL OR expected_ctc_min <= expected_ctc_max', name='check_expected_ctc_valid'),
    sa.CheckConstraint('readiness_score >= 0 AND readiness_score <= 100', name='check_readiness_score_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number'),
    sa.UniqueConstraint('user_id'),
    comment='Student profiles with academic data and external platform statistics'
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
