"""create_faculty_table

Revision ID: a60796c7eb89
Revises: 7741a795a262
Create Date: 2026-02-10 23:31:02.709947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60796c7eb89'
down_revision: Union[str, None] = '7741a795a262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.Column('can_create_assessments', sa.Boolean(), server_default=sa.text('true'), nullable=True, comment='Permission to create and manage assessments'),
    sa.Column('can_view_all_students', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('can_export_reports', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('assessments_created', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('students_mentored', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id'),
    comment='Faculty profiles with assessment creation permissions'
    )
    op.create_index(op.f('ix_faculty_id'), 'faculty', ['id'], unique=False)
    
    # Custom indexes requested by user
    op.create_index('idx_faculty_user_id', 'faculty', ['user_id'])
    op.create_index('idx_faculty_employee_id', 'faculty', ['employee_id'])
    op.create_index('idx_faculty_department', 'faculty', ['department'])
    op.create_index('idx_faculty_can_create_assessments', 'faculty', ['can_create_assessments'], postgresql_where=sa.text("can_create_assessments = TRUE"))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_faculty_can_create_assessments', table_name='faculty', postgresql_where=sa.text("can_create_assessments = TRUE"))
    op.drop_index('idx_faculty_department', table_name='faculty')
    op.drop_index('idx_faculty_employee_id', table_name='faculty')
    op.drop_index('idx_faculty_user_id', table_name='faculty')
    op.drop_index(op.f('ix_faculty_id'), table_name='faculty')
    op.drop_table('faculty')
    # ### end Alembic commands ###
