"""create_assessment_attempts_table

Revision ID: b3704704a098
Revises: 2c71cda2be60
Create Date: 2026-02-10 23:59:32.566191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3704704a098'
down_revision: Union[str, None] = '2c71cda2be60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.0'), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.0'), nullable=True),
    sa.Column('result_status', sa.String(length=50), nullable=True),
    sa.Column('questions_attempted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('questions_completed', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('proctoring_events', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='Proctoring events: [{type: "tab_switch", timestamp: "..."}]'),
    sa.Column('tab_switches', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name='check_assessment_attempts_percentage_range'),
    sa.CheckConstraint('questions_attempted >= 0 AND questions_completed >= 0 AND questions_attempted <= total_questions AND questions_completed <= questions_attempted', name='check_assessment_attempts_questions_valid'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'assessment_id', 'attempt_number', name='uq_student_assessment_attempt'),
    comment='Student assessment attempt tracking with proctoring data'
    )
    op.create_index('idx_assessment_attempts_assessment_id', 'assessment_attempts', ['assessment_id'], unique=False)
    op.create_index('idx_assessment_attempts_percentage', 'assessment_attempts', [sa.text('percentage DESC')], unique=False)
    op.create_index('idx_assessment_attempts_started_at', 'assessment_attempts', [sa.text('started_at DESC')], unique=False)
    op.create_index('idx_assessment_attempts_student_assessment', 'assessment_attempts', ['student_id', 'assessment_id'], unique=False)
    op.create_index('idx_assessment_attempts_student_id', 'assessment_attempts', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_id'), 'assessment_attempts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_attempts_id'), table_name='assessment_attempts')
    op.drop_index('idx_assessment_attempts_student_id', table_name='assessment_attempts')
    op.drop_index('idx_assessment_attempts_student_assessment', table_name='assessment_attempts')
    op.drop_index('idx_assessment_attempts_started_at', table_name='assessment_attempts')
    op.drop_index('idx_assessment_attempts_percentage', table_name='assessment_attempts')
    op.drop_index('idx_assessment_attempts_assessment_id', table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    # ### end Alembic commands ###
