"""create_assessments_table

Revision ID: bd2e785c8e0c
Revises: b5cc062c4e69
Create Date: 2026-02-10 23:46:39.237793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd2e785c8e0c'
down_revision: Union[str, None] = 'b5cc062c4e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment_type', postgresql.ENUM('practice', 'mock_test', 'placement_test', 'assignment', name='assessment_type', create_type=False), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('target_branches', sa.ARRAY(sa.String()), nullable=True, comment='Branches eligible for assessment (NULL = all)'),
    sa.Column('target_years', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('target_students', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('enable_proctoring', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('randomize_questions', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='Show questions in random order'),
    sa.Column('show_results_immediately', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('passing_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('40.0'), nullable=True),
    sa.Column('total_marks', sa.Integer(), server_default=sa.text('100'), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('total_participants', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_submissions', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.0'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('duration_minutes > 0', name='check_assessments_duration_positive'),
    sa.CheckConstraint('max_attempts > 0', name='check_assessments_max_attempts_positive'),
    sa.CheckConstraint('passing_score >= 0 AND passing_score <= 100', name='check_assessments_passing_score_range'),
    sa.CheckConstraint('start_time IS NULL OR end_time IS NULL OR start_time < end_time', name='check_assessments_time_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    comment='Assessment configurations with timing and access control'
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_slug'), 'assessments', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_slug'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
