"""create_users_table

Revision ID: f93f30e4b17c
Revises: b327aefa0e45
Create Date: 2026-02-10 22:42:08.990019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f93f30e4b17c'
down_revision: Union[str, None] = 'b327aefa0e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types explicitly before use
    conn = op.get_bind()
    
    # Check if type exists to avoid error on rerun
    # (Since this is a fresh migration, we can assume create if not exists logically, but safest is checkfirst=True with SQLAlchemy)
    
    # Define enums
    import sqlalchemy.dialects.postgresql as pg
    # Use lowercase values to match Python Enum values and server_default
    user_role = pg.ENUM('student', 'faculty', 'admin', name='user_role', create_type=False)
    user_status = pg.ENUM('active', 'inactive', 'suspended', 'pending_verification', name='user_status', create_type=False)
    
    # Create if not exists
    user_role.create(conn, checkfirst=True)
    user_status.create(conn, checkfirst=True)

    # Legacy cleanup objects may not exist in all environments.
    op.execute(sa.text("DROP INDEX IF EXISTS ix_test_items_id"))
    op.execute(sa.text("DROP TABLE IF EXISTS test_items"))
    op.add_column('users', sa.Column('role', sa.Enum('student', 'faculty', 'admin', name='user_role'), server_default=sa.text("'student'"), nullable=False, comment='User role: student, faculty, or admin'))
    op.add_column('users', sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'pending_verification', name='user_status'), server_default=sa.text("'pending_verification'"), nullable=False, comment='Account status workflow state'))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's full display name"))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True, comment='Contact phone number (E.164 format preferred)'))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('account_locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='Unique email address for login',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment='Bcrypt hashed password',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'users',
        'Core user authentication table',
        existing_comment=None,
        schema=None
    )
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table_comment(
        'users',
        existing_comment='Core user authentication table',
        schema=None
    )
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Bcrypt hashed password',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Unique email address for login',
               existing_nullable=False)
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'account_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.create_table('test_items',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_items_pkey')
    )
    op.create_index('ix_test_items_id', 'test_items', ['id'], unique=False)
    # ### end Alembic commands ###
